packageExtensions:
  "@ngrx/eslint-plugin@*":
    dependencies:
      "@typescript-eslint/utils": "*"
  "@angular-eslint/schematics@*":
    dependencies:
      "@angular-eslint/template-parser": "*"
      "@typescript-eslint/types": "*"
      "@typescript-eslint/utils": "*"
      eslint: "*"
      typescript: "~6.0.3"
